#!/usr/bin/env node

var fs=require("fs");
var version=process.argv[2];
if (!version){
  console.log("Usage: bumpVersion <version number>");
  process.exit(0);
}

var data=fs.readFileSync("./package.json");
var pkg=JSON.parse(data);
pkg.version=version;
fs.writeFileSync("./package.json",JSON.stringify(pkg));
console.log("done");